## NumPy
NumPy is a library for data science and we will learn how to use NumPy in this page

In [1]:
import numpy as np
# We called numpy library.
# When we use to numpy library skills, we will call it as "np". If we hadn't attituded of the value, we could have called as "numpy" everytime.

In [2]:
## Arrays
# Changing list to numpy array.
sampleList = [10, 20, 30]
type(sampleList)

list

In [3]:
np.array(sampleList)
## Changing to array

array([10, 20, 30])

In [4]:
type(np.array(sampleList))

numpy.ndarray

In [5]:
## Making Matrix
matrixList = [[10, 20, 30], [40, 50, 60], [70, 80, 90]]
type(matrixList)

list

In [6]:
np.array(matrixList)

array([[10, 20, 30],
       [40, 50, 60],
       [70, 80, 90]])

In [7]:
type(np.array(matrixList))

numpy.ndarray

In [8]:
## Making directly np array
# For that we use "np.arange(x,y)" method. These method using is same with ".range(x,y)" method.

np.arange(1, 15)

array([ 1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14])

In [9]:
np.arange(1, 20, 2)

array([ 1,  3,  5,  7,  9, 11, 13, 15, 17, 19])

In [12]:
#zeros and ones: Ensure as how many as say 0 or 1

np.zeros(5)

array([0., 0., 0., 0., 0.])

In [13]:
np.ones(4)

array([1., 1., 1., 1.])

In [15]:
np.zeros((9, 8))
#We can ensure a matrix

array([[0., 0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0., 0.]])

In [16]:
np.ones((15, 15))

array([[1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1., 1., 1.

In [18]:
# .linspace
## linspace method ensure an arrange how many range divide.

np.linspace(7, 9, 15)
## First number is from where to start
## Second number is from where to finish
## Third number is how many pieces to ensure

array([7.        , 7.14285714, 7.28571429, 7.42857143, 7.57142857,
       7.71428571, 7.85714286, 8.        , 8.14285714, 8.28571429,
       8.42857143, 8.57142857, 8.71428571, 8.85714286, 9.        ])

In [21]:
# eye
## eye method ensures a diagonel matrix how to ensure just 1 and 0

np.eye(5)

array([[1., 0., 0., 0., 0.],
       [0., 1., 0., 0., 0.],
       [0., 0., 1., 0., 0.],
       [0., 0., 0., 1., 0.],
       [0., 0., 0., 0., 1.]])

In [22]:
np.eye(3, 2)

array([[1., 0.],
       [0., 1.],
       [0., 0.]])

In [29]:
np.eye(4, 5, 3)
## First number ensures column wide.
## Second number ensures line wide.
## Third number ensures ones start from which cell for first line.

array([[0., 0., 0., 1., 0.],
       [0., 0., 0., 0., 1.],
       [0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0.]])

In [30]:
#RANDOM METHODS

#random.randn
## Ensures random how many numbers to want.

np.random.randn(4)

array([0.2361204 , 0.38810088, 0.04815807, 0.94944091])

In [32]:
np.random.randn(3, 2)

array([[-1.24090724, -0.01963865],
       [ 0.31098406,  1.573018  ],
       [ 1.19584885, -0.67731973]])

In [33]:
np.random.randn(3, 2, 2)

array([[[ 0.64760845,  0.89755638],
        [ 0.63973272, -0.17309622]],

       [[-0.40464191, -1.51104078],
        [ 0.50833655, -0.6309191 ]],

       [[ 0.14813981,  0.82406599],
        [ 1.49951988,  1.59523904]]])

In [34]:
np.random.randn(2, 2, 2, 2)

array([[[[-0.41668192, -0.5906889 ],
         [-0.81930013,  0.85131143]],

        [[ 1.01541244, -2.07162351],
         [ 1.02047473, -1.14128912]]],


       [[[-0.87801258,  0.13935112],
         [-1.30268212, -0.39879779]],

        [[ 0.22374174, -0.33192106],
         [ 1.68495983,  0.43819259]]]])

In [37]:
# random.randint
## Ensures random a number how which range to want.

np.random.randint(5)

1

In [38]:
np.random.randint(1, 20)

7

In [41]:
np.random.randint(1, 50, 3)
## First one is where to star random number(s).
## Second one is where to finish random number(s) except the number.
## Third one is which one numbers will write to scream.

array([26, 13,  3], dtype=int32)

In [42]:
# NumPy Array Methods

## reshape = a list resahpe and ensures a matrix.
## max = It shows the biggest value in a list.
## min = It shows the smallest value in a list.
## argmax = It shows order of the biggest value.
## argmin = It shows order of the smallest value.
## shape = It shows shape of the list.

In [47]:
a = np.arange(50)

In [48]:
a

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16,
       17, 18, 19, 20, 21, 22, 23, 24, 25, 26, 27, 28, 29, 30, 31, 32, 33,
       34, 35, 36, 37, 38, 39, 40, 41, 42, 43, 44, 45, 46, 47, 48, 49])

In [52]:
a.reshape(10, 5)
## We ensured a matrix but if we had used more than or smaller than a number that 50, we could have gotten an error.

array([[ 0,  1,  2,  3,  4],
       [ 5,  6,  7,  8,  9],
       [10, 11, 12, 13, 14],
       [15, 16, 17, 18, 19],
       [20, 21, 22, 23, 24],
       [25, 26, 27, 28, 29],
       [30, 31, 32, 33, 34],
       [35, 36, 37, 38, 39],
       [40, 41, 42, 43, 44],
       [45, 46, 47, 48, 49]])

In [54]:
a.max()

np.int64(49)

In [55]:
a.min()

np.int64(0)

In [56]:
a.argmax()

np.int64(49)

In [57]:
a.argmin()

np.int64(0)

In [58]:
a.shape

(50,)

In [59]:
aa = a.reshape(10, 5)

In [60]:
aa.shape

(10, 5)

In [61]:
## Some Array Exercies

In [62]:
aList = np.arange(0, 30, 4)

In [64]:
aList

array([ 0,  4,  8, 12, 16, 20, 24, 28])

In [65]:
aList[3:6]

array([12, 16, 20])

In [66]:
secondList = aList[3:6]

In [67]:
secondList[:] = 100

In [68]:
secondList

array([100, 100, 100])

In [69]:
aList

array([  0,   4,   8, 100, 100, 100,  24,  28])

In [70]:
## If we use this method, our original list values change too. For that we will use copy method.

In [71]:
theList = np.arange(0, 20, 2)

In [72]:
theListCopy = theList.copy()

In [73]:
slicingList = theListCopy[2:6]

In [74]:
slicingList[:] = 150

In [75]:
slicingList

array([150, 150, 150, 150])

In [76]:
theListCopy

array([  0,   2, 150, 150, 150, 150,  12,  14,  16,  18])

In [77]:
theList

array([ 0,  2,  4,  6,  8, 10, 12, 14, 16, 18])

In [78]:
## We can save our original list.

In [79]:
# Matrix

In [80]:
thisList = [[10, 20, 30], [40, 50, 60], [70, 80, 90]]
thisIsAMatrix = np.array(thisList)

In [81]:
thisIsAMatrix

array([[10, 20, 30],
       [40, 50, 60],
       [70, 80, 90]])

In [82]:
thisIsAMatrix[0]

array([10, 20, 30])

In [84]:
thisIsAMatrix[1][1]

np.int64(50)

In [86]:
thisIsAMatrix[1:, 2]

array([60, 90])

In [87]:
thisIsAMatrix[0:, 1:]

array([[20, 30],
       [50, 60],
       [80, 90]])

In [88]:
thisIsAMatrix[[0, 1]]

array([[10, 20, 30],
       [40, 50, 60]])